dist: xenial   # required for Python >= 3.7
language: python
python:
    - "3.7"
# command to install dependencies
install:
    - pip install -r requirements.txt
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux32.tar.gz
    - mkdir bin
    - tar -xzf geckodriver-v0.24.0-linux32.tar.gz -C bin
    - export PATH=$(pwd)/bin:$PATH

# command to run tests
script:
    - pytest
