version: "3.7"
services:
  db:
    image: postgres
    restart: always
    container_name: db-server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: gheorghe
