"""empty message

Revision ID: 920a33ab430c
Revises: 
Create Date: 2019-08-18 19:25:15.873192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920a33ab430c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    # ### end Alembic commands ###
